<?php

namespace Database\Seeders;

use App\Models\User;
use App\Modules\Providers\Models\ProviderProfile;
use App\Modules\ServiceCategories\Models\ServiceCategory;
use App\Modules\ServiceCategories\Models\ServiceSubcategory;
use App\Modules\Services\Models\Service;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

/**
 * Seeds a realistic set of services so the Service Management screens have
 * data to list, search, filter, approve, reject, hide, feature, and delete.
 *
 * Each service is linked to an existing provider profile and category.
 * Varies approval_status, status, is_featured, and is_hidden to exercise
 * every admin workflow the UI supports.
 *
 * Idempotent — re-running only tops up what is missing.
 */
class ServiceSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Minimum number of services to guarantee.
     */
    private const TARGET_SERVICES = 40;

    /**
     * Hand-crafted service data keyed by provider business_name for clarity.
     *
     * @var array<int, array{
     *   provider_business_name: string,
     *   category_name: string,
     *   subcategory_name?: string,
     *   title: string,
     *   description: string,
     *   price: float|null,
     *   price_type: string,
     *   currency: string,
     *   duration: string|null,
     *   location: string|null,
     *   status: string,
     *   approval_status: string,
     *   rejection_reason?: string|null,
     *   is_featured: bool,
     *   is_hidden: bool,
     *   average_rating: float,
     *   total_reviews: int,
     *   total_bookings: int,
     *   completed_bookings: int,
     * }>
     */
    private const SERVICES = [
        // ── Home Maintenance ──────────────────────────────────────────
        [
            'provider_business_name' => 'Garcia Plumbing Solutions',
            'category_name' => 'Home Maintenance',
            'subcategory_name' => 'Plumbing',
            'title' => 'Emergency Pipe Repair',
            'description' => 'Fast, reliable emergency pipe repair for residential and commercial properties. We arrive within 60 minutes and carry common parts on every truck.',
            'price' => 150.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '1-2 hours',
            'location' => 'Austin, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => true,
            'is_hidden' => false,
            'average_rating' => 4.80,
            'total_reviews' => 92,
            'total_bookings' => 310,
            'completed_bookings' => 298,
        ],
        [
            'provider_business_name' => 'Garcia Plumbing Solutions',
            'category_name' => 'Home Maintenance',
            'subcategory_name' => 'Plumbing',
            'title' => 'Water Heater Installation',
            'description' => 'Professional installation of tank and tankless water heaters. We handle permits, plumbing connections, and disposal of your old unit.',
            'price' => 850.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '3-4 hours',
            'location' => 'Austin, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.65,
            'total_reviews' => 45,
            'total_bookings' => 120,
            'completed_bookings' => 115,
        ],
        [
            'provider_business_name' => 'Wilson Electric Co.',
            'category_name' => 'Home Maintenance',
            'subcategory_name' => 'Electrical',
            'title' => 'Residential Panel Upgrade',
            'description' => 'Upgrade your electrical panel to 200 amps to support modern appliances, EV chargers, and home additions. Includes permit and inspection.',
            'price' => 2200.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '4-6 hours',
            'location' => 'Austin, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => true,
            'is_hidden' => false,
            'average_rating' => 4.90,
            'total_reviews' => 38,
            'total_bookings' => 85,
            'completed_bookings' => 82,
        ],
        [
            'provider_business_name' => 'Wilson Electric Co.',
            'category_name' => 'Home Maintenance',
            'subcategory_name' => 'Electrical',
            'title' => 'EV Charger Installation',
            'description' => 'Level 2 home EV charger installation. We assess your electrical capacity, run the circuit, and install the charger of your choice.',
            'price' => 950.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '2-3 hours',
            'location' => 'Austin, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.75,
            'total_reviews' => 22,
            'total_bookings' => 60,
            'completed_bookings' => 58,
        ],
        [
            'provider_business_name' => 'Brown Painting Co.',
            'category_name' => 'Home Maintenance',
            'subcategory_name' => 'Painting',
            'title' => 'Interior Room Painting',
            'description' => 'Professional interior painting for bedrooms, living rooms, and offices. Includes surface prep, two coats, and clean-up.',
            'price' => 60.00,
            'price_type' => 'hourly',
            'currency' => 'USD',
            'duration' => '4-8 hours',
            'location' => 'Austin, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.55,
            'total_reviews' => 67,
            'total_bookings' => 200,
            'completed_bookings' => 190,
        ],
        [
            'provider_business_name' => 'Brown Painting Co.',
            'category_name' => 'Home Maintenance',
            'subcategory_name' => 'Painting',
            'title' => 'Cabinet Refinishing',
            'description' => 'Transform your kitchen with professional cabinet refinishing. Includes sanding, priming, and two coats of durable finish.',
            'price' => 1800.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '2-3 days',
            'location' => 'Austin, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => true,
            'is_hidden' => false,
            'average_rating' => 4.85,
            'total_reviews' => 28,
            'total_bookings' => 45,
            'completed_bookings' => 44,
        ],

        // ── Cleaning Services ─────────────────────────────────────────
        [
            'provider_business_name' => 'SparkleClean Services',
            'category_name' => 'Cleaning Services',
            'subcategory_name' => 'Deep Cleaning',
            'title' => 'Deep Home Cleaning',
            'description' => 'Thorough top-to-bottom cleaning of your entire home. We tackle kitchens, bathrooms, floors, windows, and hard-to-reach areas with eco-friendly products.',
            'price' => 45.00,
            'price_type' => 'hourly',
            'currency' => 'USD',
            'duration' => '3-5 hours',
            'location' => 'San Antonio, TX',
            'status' => 'draft',
            'approval_status' => 'pending',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 0,
            'total_reviews' => 0,
            'total_bookings' => 0,
            'completed_bookings' => 0,
        ],
        [
            'provider_business_name' => 'SparkleClean Services',
            'category_name' => 'Cleaning Services',
            'subcategory_name' => 'Office Cleaning',
            'title' => 'Office Cleaning Package',
            'description' => 'Daily or weekly office cleaning for small to medium workspaces. Includes trash removal, vacuuming, mopping, and restroom sanitization.',
            'price' => 120.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '2 hours',
            'location' => 'San Antonio, TX',
            'status' => 'draft',
            'approval_status' => 'pending',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 0,
            'total_reviews' => 0,
            'total_bookings' => 0,
            'completed_bookings' => 0,
        ],
        [
            'provider_business_name' => 'SparkleClean Services',
            'category_name' => 'Cleaning Services',
            'subcategory_name' => 'Home Cleaning',
            'title' => 'Move-In / Move-Out Cleaning',
            'description' => 'Specialized cleaning for tenants and landlords. Ensure your security deposit is returned with a spotless property.',
            'price' => 250.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '4-6 hours',
            'location' => 'San Antonio, TX',
            'status' => 'published',
            'approval_status' => 'rejected',
            'rejection_reason' => 'Service description needs more detail about included areas. Please specify what is and is not covered.',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 0,
            'total_reviews' => 0,
            'total_bookings' => 0,
            'completed_bookings' => 0,
        ],

        // ── Beauty & Wellness ─────────────────────────────────────────
        [
            'provider_business_name' => 'Chen Hair Studio',
            'category_name' => 'Beauty & Wellness',
            'subcategory_name' => 'Hair Care',
            'title' => 'Balayage Hair Coloring',
            'description' => 'Hand-painted balayage highlights for a natural, sun-kissed look. Includes consultation, color application, toner, and blow-dry.',
            'price' => 180.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '2-3 hours',
            'location' => 'Dallas, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => true,
            'is_hidden' => false,
            'average_rating' => 4.92,
            'total_reviews' => 78,
            'total_bookings' => 250,
            'completed_bookings' => 245,
        ],
        [
            'provider_business_name' => 'Chen Hair Studio',
            'category_name' => 'Beauty & Wellness',
            'subcategory_name' => 'Hair Care',
            'title' => 'Keratin Smoothing Treatment',
            'description' => 'Long-lasting keratin treatment to eliminate frizz and reduce styling time. Results last up to 3 months.',
            'price' => 300.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '2-3 hours',
            'location' => 'Dallas, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.70,
            'total_reviews' => 35,
            'total_bookings' => 90,
            'completed_bookings' => 88,
        ],
        [
            'provider_business_name' => 'Morales Massage Therapy',
            'category_name' => 'Beauty & Wellness',
            'subcategory_name' => 'Massage',
            'title' => 'Deep Tissue Massage',
            'description' => 'Therapeutic deep tissue massage targeting chronic muscle tension and pain. Ideal for athletes and desk workers alike.',
            'price' => 80.00,
            'price_type' => 'hourly',
            'currency' => 'USD',
            'duration' => '1-2 hours',
            'location' => 'San Antonio, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.60,
            'total_reviews' => 55,
            'total_bookings' => 180,
            'completed_bookings' => 175,
        ],
        [
            'provider_business_name' => 'Morales Massage Therapy',
            'category_name' => 'Beauty & Wellness',
            'subcategory_name' => 'Massage',
            'title' => 'In-Home Swedish Massage',
            'description' => 'Relaxing Swedish massage in the comfort of your home. We bring the table, oils, and music. You just bring yourself.',
            'price' => 95.00,
            'price_type' => 'hourly',
            'currency' => 'USD',
            'duration' => '1-2 hours',
            'location' => 'San Antonio, TX',
            'status' => 'archived',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => true,
            'average_rating' => 4.45,
            'total_reviews' => 20,
            'total_bookings' => 50,
            'completed_bookings' => 48,
        ],
        [
            'provider_business_name' => 'Martinez Spa & Wellness',
            'category_name' => 'Beauty & Wellness',
            'subcategory_name' => 'Spa',
            'title' => 'Luxury Facial Treatment',
            'description' => 'Premium facial with cleansing, exfoliation, extraction, mask, and hydration. Customized for your skin type.',
            'price' => 120.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '1.5 hours',
            'location' => 'Austin, TX',
            'status' => 'draft',
            'approval_status' => 'pending',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 0,
            'total_reviews' => 0,
            'total_bookings' => 0,
            'completed_bookings' => 0,
        ],
        [
            'provider_business_name' => 'Green Nail Art',
            'category_name' => 'Beauty & Wellness',
            'subcategory_name' => 'Nail Care',
            'title' => 'Gel Manicure & Nail Art',
            'description' => 'Long-lasting gel manicure with custom nail art designs. Choose from hundreds of patterns or bring your own inspiration.',
            'price' => 45.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '1 hour',
            'location' => 'Dallas, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.30,
            'total_reviews' => 42,
            'total_bookings' => 130,
            'completed_bookings' => 125,
        ],

        // ── Automotive ────────────────────────────────────────────────
        [
            'provider_business_name' => 'Rodriguez Auto Care',
            'category_name' => 'Automotive',
            'subcategory_name' => 'Car Repair',
            'title' => 'Full Brake Service',
            'description' => 'Complete brake inspection, pad replacement, rotor resurfacing, and brake fluid flush. ASE-certified technicians.',
            'price' => 350.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '2-3 hours',
            'location' => 'Houston, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => true,
            'is_hidden' => false,
            'average_rating' => 4.70,
            'total_reviews' => 88,
            'total_bookings' => 320,
            'completed_bookings' => 310,
        ],
        [
            'provider_business_name' => 'Rodriguez Auto Care',
            'category_name' => 'Automotive',
            'subcategory_name' => 'Car Repair',
            'title' => 'Engine Diagnostic',
            'description' => 'Advanced computer diagnostics to pinpoint check engine light causes. We read codes, test systems, and provide a detailed report.',
            'price' => 100.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '1 hour',
            'location' => 'Houston, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.55,
            'total_reviews' => 65,
            'total_bookings' => 200,
            'completed_bookings' => 195,
        ],
        [
            'provider_business_name' => 'Hassan Towing Service',
            'category_name' => 'Automotive',
            'subcategory_name' => 'Towing',
            'title' => 'Emergency Roadside Assistance',
            'description' => '24/7 emergency roadside help including flat tire changes, jump starts, lockout assistance, and fuel delivery.',
            'price' => 75.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '30-60 minutes',
            'location' => 'Houston, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.40,
            'total_reviews' => 110,
            'total_bookings' => 450,
            'completed_bookings' => 440,
        ],
        [
            'provider_business_name' => 'Hassan Towing Service',
            'category_name' => 'Automotive',
            'subcategory_name' => 'Towing',
            'title' => 'Flatbed Towing',
            'description' => 'Safe flatbed towing for luxury, classic, and disabled vehicles. Available 24/7 within 50 miles of Houston.',
            'price' => 150.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '30-90 minutes',
            'location' => 'Houston, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.65,
            'total_reviews' => 75,
            'total_bookings' => 280,
            'completed_bookings' => 275,
        ],
        [
            'provider_business_name' => 'White Car Wash Express',
            'category_name' => 'Automotive',
            'subcategory_name' => 'Car Wash',
            'title' => 'Premium Hand Car Wash',
            'description' => 'Hand wash with pH-neutral soap, clay bar treatment, and Carnauba wax. Your car will shine like new.',
            'price' => 40.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '45-60 minutes',
            'location' => 'Fort Worth, TX',
            'status' => 'draft',
            'approval_status' => 'pending',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 0,
            'total_reviews' => 0,
            'total_bookings' => 0,
            'completed_bookings' => 0,
        ],
        [
            'provider_business_name' => 'White Car Wash Express',
            'category_name' => 'Automotive',
            'subcategory_name' => 'Car Wash',
            'title' => 'Interior Detailing',
            'description' => 'Full interior detailing including shampooing, leather conditioning, dashboard treatment, and odor elimination.',
            'price' => 120.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '2-3 hours',
            'location' => 'Fort Worth, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.50,
            'total_reviews' => 30,
            'total_bookings' => 85,
            'completed_bookings' => 82,
        ],

        // ── IT & Tech Support ─────────────────────────────────────────
        [
            'provider_business_name' => 'KimTech Solutions',
            'category_name' => 'IT & Tech Support',
            'subcategory_name' => 'Computer Repair',
            'title' => 'Laptop Screen Replacement',
            'description' => 'Cracked or broken laptop screen? We stock common sizes and can replace most screens within 24 hours.',
            'price' => 180.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '1-2 hours',
            'location' => 'Austin, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.35,
            'total_reviews' => 40,
            'total_bookings' => 110,
            'completed_bookings' => 105,
        ],
        [
            'provider_business_name' => 'KimTech Solutions',
            'category_name' => 'IT & Tech Support',
            'subcategory_name' => 'Computer Repair',
            'title' => 'Data Recovery Service',
            'description' => 'Recover lost files from failed hard drives, SSDs, and USB drives. We handle mechanical failures, accidental deletion, and corruption.',
            'price' => 250.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '1-3 days',
            'location' => 'Austin, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => true,
            'is_hidden' => false,
            'average_rating' => 4.80,
            'total_reviews' => 55,
            'total_bookings' => 140,
            'completed_bookings' => 130,
        ],
        [
            'provider_business_name' => 'Davis Network Solutions',
            'category_name' => 'IT & Tech Support',
            'subcategory_name' => 'Network Setup',
            'title' => 'Small Business Network Setup',
            'description' => 'Complete network setup for offices up to 50 devices. Includes router, switch, Wi-Fi access points, firewall configuration, and documentation.',
            'price' => 1500.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '1-2 days',
            'location' => 'San Antonio, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.75,
            'total_reviews' => 25,
            'total_bookings' => 55,
            'completed_bookings' => 52,
        ],
        [
            'provider_business_name' => 'Davis Network Solutions',
            'category_name' => 'IT & Tech Support',
            'subcategory_name' => 'Network Setup',
            'title' => 'Home Wi-Fi Optimization',
            'description' => 'Diagnose and fix dead zones, slow speeds, and connectivity issues. We optimize placement, update firmware, and configure settings.',
            'price' => 120.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '1-2 hours',
            'location' => 'San Antonio, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => true,
            'average_rating' => 4.40,
            'total_reviews' => 18,
            'total_bookings' => 45,
            'completed_bookings' => 44,
        ],

        // ── Fitness & Health ──────────────────────────────────────────
        [
            'provider_business_name' => 'FitLife Personal Training',
            'category_name' => 'Fitness & Health',
            'subcategory_name' => 'Personal Training',
            'title' => '12-Week Weight Loss Program',
            'description' => 'Structured 12-week program combining strength training, cardio, and nutrition guidance. Includes weekly check-ins and plan adjustments.',
            'price' => 55.00,
            'price_type' => 'hourly',
            'currency' => 'USD',
            'duration' => '1 hour per session',
            'location' => 'Fort Worth, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.60,
            'total_reviews' => 32,
            'total_bookings' => 95,
            'completed_bookings' => 88,
        ],
        [
            'provider_business_name' => 'FitLife Personal Training',
            'category_name' => 'Fitness & Health',
            'subcategory_name' => 'Personal Training',
            'title' => 'Post-Rehab Strength Training',
            'description' => 'Specialized strength training for recovering from surgery or injury. Works alongside your physiotherapist for safe, effective progress.',
            'price' => 65.00,
            'price_type' => 'hourly',
            'currency' => 'USD',
            'duration' => '1 hour',
            'location' => 'Fort Worth, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.70,
            'total_reviews' => 15,
            'total_bookings' => 40,
            'completed_bookings' => 38,
        ],
        [
            'provider_business_name' => 'Sharma Yoga Studio',
            'category_name' => 'Fitness & Health',
            'subcategory_name' => 'Yoga',
            'title' => 'Private Vinyasa Yoga Session',
            'description' => 'One-on-one vinyasa yoga tailored to your level and goals. Perfect for beginners or practitioners seeking personalized attention.',
            'price' => 70.00,
            'price_type' => 'hourly',
            'currency' => 'USD',
            'duration' => '1 hour',
            'location' => 'Dallas, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => true,
            'is_hidden' => false,
            'average_rating' => 4.95,
            'total_reviews' => 62,
            'total_bookings' => 200,
            'completed_bookings' => 198,
        ],
        [
            'provider_business_name' => 'Sharma Yoga Studio',
            'category_name' => 'Fitness & Health',
            'subcategory_name' => 'Yoga',
            'title' => 'Corporate Wellness Yoga',
            'description' => 'Group yoga sessions for offices and teams. Reduce stress, improve posture, and boost morale. Mats and equipment provided.',
            'price' => 200.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '1 hour',
            'location' => 'Dallas, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.80,
            'total_reviews' => 20,
            'total_bookings' => 50,
            'completed_bookings' => 48,
        ],
        [
            'provider_business_name' => 'Thompson Physiotherapy',
            'category_name' => 'Fitness & Health',
            'subcategory_name' => 'Physiotherapy',
            'title' => 'Sports Injury Rehabilitation',
            'description' => 'Comprehensive rehabilitation for sports injuries including ACL tears, rotator cuff, and ankle sprains. Evidence-based treatment plans.',
            'price' => 110.00,
            'price_type' => 'hourly',
            'currency' => 'USD',
            'duration' => '45-60 minutes',
            'location' => 'Houston, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.85,
            'total_reviews' => 48,
            'total_bookings' => 160,
            'completed_bookings' => 155,
        ],
        [
            'provider_business_name' => 'Thompson Physiotherapy',
            'category_name' => 'Fitness & Health',
            'subcategory_name' => 'Physiotherapy',
            'title' => 'Dry Needling Therapy',
            'description' => 'Targeted dry needling to relieve chronic muscle pain and trigger points. Effective for tension headaches, back pain, and shoulder impingement.',
            'price' => 90.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => '30-45 minutes',
            'location' => 'Houston, TX',
            'status' => 'archived',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => true,
            'average_rating' => 4.50,
            'total_reviews' => 22,
            'total_bookings' => 65,
            'completed_bookings' => 63,
        ],

        // ── Event Services ────────────────────────────────────────────
        [
            'provider_business_name' => 'Anderson Catering',
            'category_name' => 'Event Services',
            'subcategory_name' => 'Catering',
            'title' => 'BBQ Catering Package',
            'description' => 'Authentic Texas BBQ catering for parties of 20-200. Brisket, ribs, sausage, sides, and all the fixings. Delivery and setup included.',
            'price' => 35.00,
            'price_type' => 'custom',
            'currency' => 'USD',
            'duration' => 'Per person',
            'location' => 'Fort Worth, TX',
            'status' => 'draft',
            'approval_status' => 'pending',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 0,
            'total_reviews' => 0,
            'total_bookings' => 0,
            'completed_bookings' => 0,
        ],
        [
            'provider_business_name' => 'Anderson Catering',
            'category_name' => 'Event Services',
            'subcategory_name' => 'Catering',
            'title' => 'Elegant Plated Dinner Service',
            'description' => 'Formal plated dinner catering for weddings, galas, and corporate events. Customizable 3-5 course menus with vegetarian and vegan options.',
            'price' => 75.00,
            'price_type' => 'custom',
            'currency' => 'USD',
            'duration' => 'Per person',
            'location' => 'Fort Worth, TX',
            'status' => 'published',
            'approval_status' => 'rejected',
            'rejection_reason' => 'Pricing information is incomplete. Please provide a base per-person rate and minimum guest count.',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 0,
            'total_reviews' => 0,
            'total_bookings' => 0,
            'completed_bookings' => 0,
        ],
        [
            'provider_business_name' => 'Taylor Photography',
            'category_name' => 'Event Services',
            'subcategory_name' => 'Photography',
            'title' => 'Wedding Photography Package',
            'description' => 'Full-day wedding photography coverage. Includes engagement session, two photographers, edited digital gallery, and print rights.',
            'price' => 2500.00,
            'price_type' => 'fixed',
            'currency' => 'USD',
            'duration' => 'Full day (8-10 hours)',
            'location' => 'Houston, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => true,
            'is_hidden' => false,
            'average_rating' => 4.90,
            'total_reviews' => 45,
            'total_bookings' => 120,
            'completed_bookings' => 118,
        ],
        [
            'provider_business_name' => 'Taylor Photography',
            'category_name' => 'Event Services',
            'subcategory_name' => 'Photography',
            'title' => 'Corporate Event Photography',
            'description' => 'Professional photography for conferences, product launches, and corporate events. Fast turnaround on edited images.',
            'price' => 120.00,
            'price_type' => 'hourly',
            'currency' => 'USD',
            'duration' => 'Minimum 3 hours',
            'location' => 'Houston, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.65,
            'total_reviews' => 28,
            'total_bookings' => 70,
            'completed_bookings' => 68,
        ],

        // ── Education & Tutoring ──────────────────────────────────────
        [
            'provider_business_name' => 'Lee Math Tutoring',
            'category_name' => 'Education & Tutoring',
            'subcategory_name' => 'Math Tutoring',
            'title' => 'SAT Math Prep Course',
            'description' => 'Intensive SAT math preparation covering algebra, problem solving, and advanced math. Includes practice tests and personalized study plans.',
            'price' => 50.00,
            'price_type' => 'hourly',
            'currency' => 'USD',
            'duration' => '1 hour',
            'location' => 'Austin, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.70,
            'total_reviews' => 35,
            'total_bookings' => 90,
            'completed_bookings' => 85,
        ],
        [
            'provider_business_name' => 'Lee Math Tutoring',
            'category_name' => 'Education & Tutoring',
            'subcategory_name' => 'Math Tutoring',
            'title' => 'Calculus Tutoring',
            'description' => 'One-on-one calculus tutoring for high school and college students. Covers limits, derivatives, integrals, and series.',
            'price' => 55.00,
            'price_type' => 'hourly',
            'currency' => 'USD',
            'duration' => '1 hour',
            'location' => 'Austin, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.55,
            'total_reviews' => 20,
            'total_bookings' => 55,
            'completed_bookings' => 52,
        ],
        [
            'provider_business_name' => 'Nguyen Language Academy',
            'category_name' => 'Education & Tutoring',
            'subcategory_name' => 'Language Classes',
            'title' => 'Vietnamese Conversation Classes',
            'description' => 'Practice Vietnamese conversation with a native speaker. Small groups or private sessions. Suitable for beginners to advanced learners.',
            'price' => 45.00,
            'price_type' => 'hourly',
            'currency' => 'USD',
            'duration' => '1 hour',
            'location' => 'Dallas, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => false,
            'is_hidden' => false,
            'average_rating' => 4.45,
            'total_reviews' => 18,
            'total_bookings' => 45,
            'completed_bookings' => 43,
        ],
        [
            'provider_business_name' => 'Nguyen Language Academy',
            'category_name' => 'Education & Tutoring',
            'subcategory_name' => 'Language Classes',
            'title' => 'Business English Workshop',
            'description' => 'Intensive business English for professionals. Focus on presentations, negotiations, emails, and meeting communication.',
            'price' => 60.00,
            'price_type' => 'hourly',
            'currency' => 'USD',
            'duration' => '2 hours',
            'location' => 'Dallas, TX',
            'status' => 'published',
            'approval_status' => 'approved',
            'is_featured' => true,
            'is_hidden' => false,
            'average_rating' => 4.75,
            'total_reviews' => 22,
            'total_bookings' => 55,
            'completed_bookings' => 53,
        ],
    ];

    public function run(): void
    {
        $actor = User::query()->whereHas('roles')->first();

        $existing = Service::count();
        $missing = max(0, self::TARGET_SERVICES - $existing);

        if ($missing === 0) {
            $this->command?->info("Already {$existing} services — nothing to seed.");

            return;
        }

        $toCreate = array_slice(self::SERVICES, 0, $missing);

        // Cache provider profiles and categories to avoid repeated queries.
        $providers = ProviderProfile::query()
            ->with('user:id')
            ->get()
            ->keyBy('business_name');

        $categories = ServiceCategory::query()
            ->with('subcategories:id,category_id,name')
            ->get()
            ->keyBy('name');

        $created = 0;

        foreach ($toCreate as $data) {
            $provider = $providers->get($data['provider_business_name']);

            if (! $provider) {
                $this->command?->warn("Provider \"{$data['provider_business_name']}\" not found — skipping \"{$data['title']}\".");

                continue;
            }

            $category = $categories->get($data['category_name']);

            if (! $category) {
                $this->command?->warn("Category \"{$data['category_name']}\" not found — skipping \"{$data['title']}\".");

                continue;
            }

            $subcategory = null;

            if (! empty($data['subcategory_name'])) {
                $subcategory = $category->subcategories->firstWhere('name', $data['subcategory_name']);
            }

            // Skip duplicates.
            if (Service::where('title', $data['title'])->where('provider_id', $provider->id)->exists()) {
                continue;
            }

            $createdAt = fake()->dateTimeBetween('-180 days', '-5 days');
            $isApproved = $data['approval_status'] === 'approved';

            Service::create([
                'provider_id' => $provider->id,
                'category_id' => $category->id,
                'subcategory_id' => $subcategory?->id,
                'title' => $data['title'],
                'description' => $data['description'],
                'price' => $data['price'],
                'price_type' => $data['price_type'],
                'currency' => $data['currency'],
                'duration' => $data['duration'],
                'location' => $data['location'],
                'status' => $data['status'],
                'approval_status' => $data['approval_status'],
                'rejection_reason' => $data['rejection_reason'] ?? null,
                'is_featured' => $data['is_featured'],
                'is_hidden' => $data['is_hidden'],
                'total_bookings' => $data['total_bookings'],
                'completed_bookings' => $data['completed_bookings'],
                'average_rating' => $data['average_rating'],
                'total_reviews' => $data['total_reviews'],
                'created_by' => $actor?->id,
                'updated_by' => $actor?->id,
                'approved_by' => $isApproved ? $actor?->id : null,
                'approved_at' => $isApproved ? fake()->dateTimeBetween($createdAt, 'now') : null,
                'created_at' => $createdAt,
                'updated_at' => fake()->dateTimeBetween($createdAt, 'now'),
            ]);

            $created++;
        }

        $this->command?->info("Seeded {$created} services — total: ".Service::count().'.');
    }
}
